# The interval at which the latest checkpoint timestamp is updated.
checkpoint_update_interval: '10s'

# The interval at which the reference gas price is updated.
rgp_update_interval: '60s'

# The allowed staleness of the full node.
# When setting this duration, note a timestamp on Sui may be a bit late compared to the current time, but it shouldn't be more than a second.
allowed_staleness: '120s'

# The maximum time to live for a session key.
session_key_ttl_max: '30m'

# The minimum version of the SDK that is required to use this service.
sdk_version_requirement: ">=0.4.5"

# The on-chain object ID of the key server object.
key_server_object_id: "0x0"

# The network to use
network: "testnet"